/**
 * One-time (re-runnable) self-hosting of Google Fonts.
 *
 * Downloads only the `latin` and `latin-ext` woff2 subsets for the three brand
 * families as variable fonts, saves them to public/fonts/, and writes a local
 * public/fonts/fonts.css with rewritten URLs. Run with: node scripts/fetch-fonts.mjs
 *
 * Fonts change rarely, so the output is committed; this script is only re-run to
 * refresh versions. The build does NOT depend on it.
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const fontsDir = path.resolve(__dirname, '..', 'public', 'fonts')

const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36'

const FAMILIES = [
  {
    slug: 'fraunces',
    url: 'https://fonts.googleapis.com/css2?family=Fraunces:ital,opsz,wght@0,9..144,300..900;1,9..144,300..900&display=swap',
  },
  { slug: 'inter', url: 'https://fonts.googleapis.com/css2?family=Inter:wght@300..700&display=swap' },
  { slug: 'jetbrains-mono', url: 'https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400..600&display=swap' },
]

const KEEP = new Set(['latin', 'latin-ext'])

async function fetchText(url) {
  const res = await fetch(url, { headers: { 'User-Agent': UA } })
  if (!res.ok) throw new Error(`Fetch failed ${res.status} for ${url}`)
  return res.text()
}

async function downloadTo(url, dest) {
  const res = await fetch(url, { headers: { 'User-Agent': UA } })
  if (!res.ok) throw new Error(`Download failed ${res.status} for ${url}`)
  const buf = Buffer.from(await res.arrayBuffer())
  fs.writeFileSync(dest, buf)
  return buf.length
}

/** Split a css2 response into { subset, block } items using the `/* subset *\/` comments. */
function parseBlocks(css) {
  const parts = css.split(/\/\*\s*([\w-]+)\s*\*\//).slice(1)
  const items = []
  for (let i = 0; i < parts.length; i += 2) {
    items.push({ subset: parts[i].trim(), block: parts[i + 1] })
  }
  return items
}

async function main() {
  fs.mkdirSync(fontsDir, { recursive: true })
  let cssOut = '/* Self-hosted brand fonts (latin + latin-ext). Generated by scripts/fetch-fonts.mjs */\n\n'
  const written = []

  for (const family of FAMILIES) {
    const css = await fetchText(family.url)
    for (const { subset, block } of parseBlocks(css)) {
      if (!KEEP.has(subset)) continue
      const urlMatch = block.match(/src:\s*url\((https:\/\/[^)]+\.woff2)\)/)
      if (!urlMatch) continue
      const isItalic = /font-style:\s*italic/.test(block)
      const fileName = `${family.slug}-${subset}${isItalic ? '-italic' : ''}.woff2`
      const dest = path.join(fontsDir, fileName)
      const bytes = await downloadTo(urlMatch[1], dest)
      written.push({ fileName, bytes })

      const localBlock = block.replace(urlMatch[1], `/fonts/${fileName}`)
      cssOut += `/* ${family.slug} ${subset}${isItalic ? ' italic' : ''} */${localBlock}`
    }
  }

  fs.writeFileSync(path.join(fontsDir, 'fonts.css'), cssOut, 'utf8')
  console.log('[fonts] wrote public/fonts/fonts.css')
  for (const w of written) console.log(`[fonts] ${w.fileName} (${(w.bytes / 1024).toFixed(1)} KB)`)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
